# config file for testing
# filename should be application-gorm.yml

gorm:
  type: mysql
  host: ${MYSQL_HOST:mysql}
  port: 3306
  database: ${app.name:test}
  username: ${MYSQL_USERNAME:root}
  password: ${MYSQL_PASSWORD:123456}
  charset: utf8
  parseTime: true
  loc: Asia/Shanghai
  config:
    decrypt: true

